INSERT INTO genre(name) VALUES ('Pop');
INSERT INTO genre(name) VALUES ('Jazz');
INSERT INTO genre(name) VALUES ('Rock and roll');
INSERT INTO genre(name) VALUES ('Blues');
INSERT INTO genre(name) VALUES ('Electro');

INSERT INTO performer(name) VALUES ('The Beatles');
INSERT INTO performer(name) VALUES ('Michael Jackson');
INSERT INTO performer(name) VALUES ('Miles Davis');
INSERT INTO performer(name) VALUES ('Louis Armstrong');
INSERT INTO performer(name) VALUES ('Elvis Presley');
INSERT INTO performer(name) VALUES ('Chuck Berry');
INSERT INTO performer(name) VALUES ('Bob Dylan');
INSERT INTO performer(name) VALUES ('DaftPunk');

INSERT INTO genre_performer VALUES (1, 1);
INSERT INTO genre_performer VALUES (1, 2);
INSERT INTO genre_performer VALUES (2, 3);
INSERT INTO genre_performer VALUES (2, 4);
INSERT INTO genre_performer VALUES (3, 5);
INSERT INTO genre_performer VALUES (3, 6);
INSERT INTO genre_performer VALUES (4, 7);
INSERT INTO genre_performer VALUES (5, 8);
INSERT INTO genre_performer VALUES (3, 1);
INSERT INTO genre_performer VALUES (4, 5);
INSERT INTO genre_performer VALUES (4, 6);

INSERT INTO album(name, year_of_issue) VALUES ('Abbey Road', 1969);
INSERT INTO album(name, year_of_issue) VALUES ('Off the Wall', 1979);
INSERT INTO album(name, year_of_issue) VALUES ('Kind of Blue', 1959);
INSERT INTO album(name, year_of_issue) VALUES ('What A Wonderful World', 1967);
INSERT INTO album(name, year_of_issue) VALUES ('Blue Hawaii', 1961);
INSERT INTO album(name, year_of_issue) VALUES ('Berry Is On Top', 1959);
INSERT INTO album(name, year_of_issue) VALUES ('The Freewheelin Bob Dylan', 1963);
INSERT INTO album(name, year_of_issue) VALUES ('Discovery', 2018);

INSERT INTO performer_album VALUES (1, 1);
INSERT INTO performer_album VALUES (2, 2);
INSERT INTO performer_album VALUES (3, 3);
INSERT INTO performer_album VALUES (4, 4);
INSERT INTO performer_album VALUES (5, 5);
INSERT INTO performer_album VALUES (6, 6);
INSERT INTO performer_album VALUES (7, 7);
INSERT INTO performer_album VALUES (8, 8);
INSERT INTO performer_album VALUES (3, 4);

INSERT INTO song(name, duration, album_id) VALUES ('Something = Algo', 183, 1);
INSERT INTO song(name, duration, album_id) VALUES ('Polythene Pam', 73, 1);
INSERT INTO song(name, duration, album_id) VALUES ('Rock with You', 220, 2);
INSERT INTO song(name, duration, album_id) VALUES ('Get on the Floor', 284, 2);
INSERT INTO song(name, duration, album_id) VALUES ('So What', 567, 3);
INSERT INTO song(name, duration, album_id) VALUES ('Freddie Freeloader', 585, 3);
INSERT INTO song(name, duration, album_id) VALUES ('What A Wonderful my World', 136, 4);
INSERT INTO song(name, duration, album_id) VALUES ('Cabaret', 164, 4);
INSERT INTO song(name, duration, album_id) VALUES ('Blue Hawaii', 155, 5);
INSERT INTO song(name, duration, album_id) VALUES ('Almost Grown', 142, 6);
INSERT INTO song(name, duration, album_id) VALUES ('Carol', 141, 6);
INSERT INTO song(name, duration, album_id) VALUES ('Blowin'' in the Wind', 263, 7);
INSERT INTO song(name, duration, album_id) VALUES ('Girl From the North Country', 200, 7);
INSERT INTO song(name, duration, album_id) VALUES ('One More Time', 320, 8);
INSERT INTO song(name, duration, album_id) VALUES ('Aerodynamic', 270, 8);

INSERT INTO collection(name, year_of_issue) VALUES ('Long songs', 2002);
INSERT INTO collection(name, year_of_issue) VALUES ('Old songs', 2010);
INSERT INTO collection(name, year_of_issue) VALUES ('Hits of the 70''s and 80''s', 2000);
INSERT INTO collection(name, year_of_issue) VALUES ('Jazz songs', 1991);
INSERT INTO collection(name, year_of_issue) VALUES ('Songs of the 2000s', 2020);
INSERT INTO collection(name, year_of_issue) VALUES ('Different', 2005);
INSERT INTO collection(name, year_of_issue) VALUES ('Pop songs', 2018);
INSERT INTO collection(name, year_of_issue) VALUES ('Songs from the 50s', 2000);

INSERT INTO collection_song VALUES (5, 1);
INSERT INTO collection_song VALUES (6, 1);
INSERT INTO collection_song VALUES (5, 2);
INSERT INTO collection_song VALUES (6, 2);
INSERT INTO collection_song VALUES (9, 2);
INSERT INTO collection_song VALUES (10, 2);
INSERT INTO collection_song VALUES (11, 2);
INSERT INTO collection_song VALUES (3, 3);
INSERT INTO collection_song VALUES (4, 3);
INSERT INTO collection_song VALUES (5, 4);
INSERT INTO collection_song VALUES (6, 4);
INSERT INTO collection_song VALUES (7, 4);
INSERT INTO collection_song VALUES (8, 4);
INSERT INTO collection_song VALUES (14, 5);
INSERT INTO collection_song VALUES (15, 5);
INSERT INTO collection_song VALUES (13, 6);
INSERT INTO collection_song VALUES (4, 6);
INSERT INTO collection_song VALUES (7, 6);
INSERT INTO collection_song VALUES (1, 7);
INSERT INTO collection_song VALUES (2, 7);
INSERT INTO collection_song VALUES (3, 7);
INSERT INTO collection_song VALUES (4, 7);
INSERT INTO collection_song VALUES (5, 8);
INSERT INTO collection_song VALUES (6, 8);
INSERT INTO collection_song VALUES (10, 8);
INSERT INTO collection_song VALUES (11, 8);